// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// phishingCardsDao is the data access object for the table hg_phishing_cards.
// You can define custom methods on it to extend its functionality as needed.
type phishingCardsDao struct {
	*internal.PhishingCardsDao
}

var (
	// PhishingCards is a globally accessible object for table hg_phishing_cards operations.
	PhishingCards = phishingCardsDao{internal.NewPhishingCardsDao()}
)

// Add your custom methods and functionality below.
